---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmap
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.io.controlplane.io
  resources:
  - terraformrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.io.controlplane.io
  resources:
  - terraformrequests/finalizers
  verbs:
  - update
- apiGroups:
  - controlplane.io.controlplane.io
  resources:
  - terraformrequests/status
  verbs:
  - get
  - patch
  - update
