# This rule is not used by the project controlplane itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the controlplane.io.controlplane.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controlplane
    app.kubernetes.io/managed-by: kustomize
  name: terraformrequest-editor-role
rules:
- apiGroups:
  - controlplane.io.controlplane.io
  resources:
  - terraformrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.io.controlplane.io
  resources:
  - terraformrequests/status
  verbs:
  - get
