apiVersion: controlplane.io.controlplane.io/v1
kind: TerraformRequest
metadata:
  name: example
  namespace: default
spec:
  credentialSecretName: aws-credentials
  inline: |
    provider "aws" {
      region = "us-east-2"
    }
    data "aws_iam_policy_document" "instance_assume_role_policy" {
      statement {
        actions = ["sts:AssumeRole"]

        principals {
          type        = "Service"
          identifiers = ["ec2.amazonaws.com"]
        }
      }
    }
    resource "aws_iam_role" "instance" {
      name               = "instance_role"
      path               = "/system/"
      assume_role_policy = data.aws_iam_policy_document.instance_assume_role_policy.json
    }
    